# Generated by Django 5.0.7 on 2024-09-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDetails',
            fields=[
                ('User_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=20)),
                ('User_Password', models.CharField(max_length=20)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
