# Generated by Django 5.0.7 on 2024-09-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_usersdetails_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetails',
            name='active',
            field=models.CharField(choices=[(True, 'True'), (False, 'False')], default=True, max_length=10),
        ),
    ]
